service: episodehunter

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

environment: ${file(environment_${opt:stage}.yml)}

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**

functions:
  ping:
    handler: dist/handler.ping
    events:
      - http:
          path: ping
          method: get
  scrobble:
    handler: dist/scrobble/episode/handler.scrobble
    events:
      - http:
          path: scrobble/episode
          method: post
          authorizer: auth
  auth:
    handler: dist/auth/handler.auth
