service: episodehunter

custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  environment: ${file(env.yml):${self:custom.stage}}

plugins:
  - serverless-offline

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**
    - env.yml

functions:
  ping:
    handler: dist/handler.ping
    events:
      - http:
          path: ping
          method: get
  scrobble:
    handler: dist/scrobble/episode/handler.scrobble
    events:
      - http:
          path: scrobble/episode
          method: post
          authorizer: auth
  auth:
    handler: dist/auth/handler.auth
